### ISSUE TITLE
Question about named argument

### ISSUE THREAD

**Issue by andrewbest** [ylikx/forpy#16]
I'm not sure if it's possible to name an argument. For example, in the imshow matplotlib call there are named arguments that are optional. Is it possible to name an argument without adding other optional arguments? I don't see how to do this with tuple. These are not kwargs but it would be nice if dictionaries could be used for arguments.

**Comment by ylikx** [comment]
It should be possible to add those arguments to the keyword arguments dictionary.

**Comment by andrewbest** [comment]
Okay, I tried again. I had missed the dict_create.

**Comment by ylikx** [comment]
Great, thanks for the question!
