### ISSUE TITLE
Segmentation Fault when working with arrays 

### ISSUE THREAD

**Issue by andpalacios** [ylikx/forpy#19]
Hello, 
I'm having the following error when trying to run the Working with arrays examples. Specifically when using the functions: "ndarray_create", "ndarray_create_nocopy". 
Do you know what might be causing this? I'm using Gfortran and Python3. Your examples with the tuples and dictionaries work well. 
Thank you! 
Regards, 
Andrea
------------------------------------------------
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f4541cf031a
#1  0x7f4541cef503
#2  0x7f4541922f1f
#3  0x7f45422c18ea
#4  0x55e3e0ec13b4
#5  0x55e3e0ebc437
#6  0x55e3e0ead2ed
#7  0x55e3e0ead715
#8  0x55e3e0eaf5f0
#9  0x55e3e0eb8e13
#10  0x55e3e0ea8f5a
#11  0x55e3e0ea8f9b
#12  0x7f4541905b96
#13  0x55e3e0ea8da9
#14  0xffffffffffffffff
Segmentation fault (core dumped)
------------------------------------------------

**Comment by ylikx** [comment]
Hi,
it could be that numpy is not installed. Check the error code returned by `forpy_initialize`.
If that does not solve the problem, check the other error codes (check out the matplotlib example for a method to do this). You can also insert `call err_print` statements to help with debugging. You can also try compiling with the compiler-option `-g` and run in the `gdb` debugger to get a more informative backtrace.
