### ISSUE TITLE
Is it valid to use the same tuple by setting different values repeatedly?

### ISSUE THREAD

**Issue by septcolor** [ylikx/forpy#24]
In this code, I am trying to call Numpy `np.sin(x)` and `np.cos(x)` for different
value of `x`. Here, I am re-using the `args` variable by overwriting its content. Is this a valid approach, or do we need to re-initialize `args` by calling `args % destroy` every time `setitem()` is called?

```fortran
type(module_py) :: np
type(tuple) :: args
type(object) :: ret
integer :: ierr
real(8) :: x

ierr = import_py( np, "numpy" )
ierr = tuple_create( args, 1 )   !! args = (*,) (1-tuple)
ierr = args % setitem( 0, 1.0d0 / 3.0d0 )   !! args[ 0 ] = 1.0 / 3.0
ierr = call_py( ret, np, "sin", args= args )   !! ret = np.sin( *args )
ierr = print_py( ret )

ierr = args % setitem( 0, 1.0d0 / 5.0d0 )   !! args[ 0 ] = 1.0 / 5.0
! ierr = args % setitem( 0, 100 )  !! this also works
ierr = call_py( ret, np, "cos", args= args )   !! ret = np.cos( *args )
ierr = print_py( ret )
```

(Also, I am wondering where is the best platform to ask this kind of question... e.g., Github issues, StackOverflow, Fortran Discourse, or comp.lang.fortran?)

**Comment by ylikx** [comment]
Good question. My understanding was that once you use a tuple, you must not modify it. Therefore I would not use the approach of your example. However, I couldn't find a source that explicitly forbids what you are doing.
The underlying Python C API function `PyTuple_SetItem` gives an error if the reference count of the tuple is not equal to 1. One could write a function that keeps a reference to its argument tuple, then the second `setitem` would fail. In your case the refcount is obviously 1 and I can't think of a counter-example in that case.
In the C API docs, for a different function related to modifying tuples it says:

> Because tuples are supposed to be immutable, this should only be used if there is only one reference to the object. Do not use this if the tuple may already be known to some other part of the code. [1] 

[1] https://docs.python.org/3.8/c-api/tuple.html#c._PyTuple_Resize

**Comment by ylikx** [comment]
Concerning your second question:
Github issues has the advantage that there will be a notification if someone opens an issue. You can also use e-mail, since the amount of questions at the moment is manageable. For the other platforms, I don't know if there would be a lot of people answering forpy questions on the other platforms. Personally I usually don't check them for forpy questions (maybe I should?).

**Comment by ylikx** [comment]
In summary: I think it's OK to use the same tuple, as long as there is only 1 reference to the tuple, but I'm not 100% sure.
