### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by lkampoli** [ylikx/forpy#29]
Hello,
thank you very much for this valuable project! 
I have a general question about timing. Have you done any time profiling of the different function calls?
I'm quite sensible to the topic because I plan to use forpy to call ML/NN within intensive Fortran sections.

Kind regards,
Lorenzo Campoli

**Comment by ylikx** [comment]
Hi,
I did not do profiling of the function calls. Typically the most called functions will be the ones that just wrap one Python C API call, therefore I don't expect too much overhead. Converting to and from long Fortran strings could be an issue, since that involves copying the whole string.

**Comment by lkampoli** [comment]
Thank you.
