### ISSUE TITLE
Values transferred with np.copy() do not reach Fortran

### ISSUE THREAD

**Issue by suessspeise** [ylikx/forpy#36]
I am trying to perform a simple matrix multiplication in embedded Python. This works just fine with return values. With in place operation on pointer arrays (`ndarray_create_nocopy()`) the results of computation done in Python do not necessarily end up in the Fortran representation of the array.

I do this on the Fortran side:
```fortran
e = ndarray_create_nocopy(nd_A, A)
e = ndarray_create_nocopy(nd_B, B)
e = ndarray_create_nocopy(nd_C, C)
e = tuple_create(args,3)
e = args%setitem(0,nd_A)
e = args%setitem(1,nd_B)
e = args%setitem(2,nd_C)
e = call_py(receive_obj, wrapper, "matmul_copy", args)
```
With this Python function being called:
```python
def matmul_copy(a, b, c, *args, **kwargs):
    d = np.matmul(a, b)
    c = np.copy(d) # or d.copy()
```
On the Python side, both `c` and `d` show the expected values. On the fortran side `c` will just consist of zero values. A element wise copy of the array solves, the problem (but is substantially slower).
As mentioned above, this is not a pressing issue, as it will work with return values. Nevertheless: could you help me understand this behaviour?

**Comment by ylikx** [comment]
In your Python code, after the last line, `c` does not refer to the original numpy array anymore. Through `np.copy` a new numpy array was created and the assignment binds the (local) name `c` to this new array.
As you have noticed, if you make an elementwise copy in the last line:
```Python
c[...] = d
```
then the contents of the original array would be modified.

**Comment by suessspeise** [comment]
Thank you for that explanation. 

Also the indexing solution is great. It works and is even faster, than the return solution.
