### ISSUE TITLE
Time measurements / wallclock time failure

### ISSUE THREAD

**Issue by suessspeise** [ylikx/forpy#39]
Hi, 
I tried to measure the performance of matrix multiplication of Numpy's `np.matmul()` embedded with Forpy in Fortran vs. Fortrans intrinsic `matmul()`. As this is aimed at a parallel environment I was initially using a wallclock based timer. But apparently wallclock based timing fails to capture the time consumption of embedded Python and display underestimated runtimes. 
Cpu time based approaches seem to give valid results (in a non parallel test case). 

![cpu time vs. wallclock time](https://raw.githubusercontent.com/suessspeise/matmul_benchmark/master/img/cpu_time_vs_wallclock.png)

Do you have an idea, why the wallclock timer does not work here? 

This is work in progress, but if you are interested in source code:
https://github.com/suessspeise/matmul_benchmark

**Comment by suessspeise** [comment]
I am still not 100 percent sure about this, but I think the problem might have been, that the used BLAS libraries were secretly multithreading. I tried to hinder that with the use of environment variables but without effect (`OMP_NUM_THREADS = 1, OPENBLAS_NUM_THREADS = 1, NUMEXPR_NUM_THREADS = 1, VECLIB_MAXIMUM_THREADS = 1, MKL_NUM_THREADS = 1, MPI_NUM_THREADS = 1`; [based on this numpy issue](https://github.com/numpy/numpy/issues/11826i)). Using slurm with `--threads-per-core=1` seems to make the behaviour more consistent.

Would you like to add something? Otherwise I would close the issue.

**Comment by ylikx** [comment]
Hi, I didn't have time to look into this issue - thanks for your findings! If I understand correctly, the wallclock timer does not measure the total time of all the threads?
