### ISSUE TITLE
Prediction using keras

### ISSUE THREAD

**Issue by sidmishfpl1801** [ylikx/forpy#47]

**Comment by ylikx** [comment]
The error says that there is no call_py function specifically for ndarrays as first argument. You can however use an `object` and the use `cast` to create a `ndarray`

```Fortran
type(object) :: ypred_obj
!...
ierror = call_py(ypred_obj, loaded_model, "predict",  args)
ierror = cast(Ypred, ypred_obj)
```

**Comment by sidmishfpl1801** [comment]
In the following code i want that Ypred should have the data of Ypred_arr but i am not able to get it in it , i have tried different ways like using ndarray_create_nocopy but it doesn't worked like

```
module UNET_module
    use forpy_mod
	use ntypes,     only: i4, r8
    implicit none

    integer :: ierror
contains

    subroutine UNET_summary(var, x, Ypred)
        character(len=*), intent(in) :: var
        real(r8), dimension(16, 32, 32) :: x
        real(r8), dimension(16, 32, 32) :: Ypred

        type(module_py) :: keras_models
        type(object) :: loaded_model, ypred_obj
        type(tuple) :: args
        type(ndarray) :: xtest, Ypred_arr

        ierror = forpy_initialize()

        ierror = import_py(keras_models, "keras.models") 
        ierror = tuple_create(args, 1)
        ierror = args%setitem(0, "../unet_var" // var // ".h5")
        ierror = call_py(loaded_model, keras_models, "load_model", args)
        !ierror = call_py_noret(loaded_model, "summary")
        ierror = ndarray_create(xtest, x)

        ierror = args%setitem(0,xtest)
        ierror = call_py(ypred_obj, loaded_model, "predict",  args)
        ierror = ndarray_create_nocopy(Ypred_arr, Ypred)
        ierror = cast(Ypred_arr, Ypred_obj)
        write(*,*), Ypred
        call err_print

        call keras_models%destroy
        call loaded_model%destroy
        call ypred_obj%destroy
        call ypred_arr%destroy
        call args%destroy
        call xtest%destroy
        !call forpy_finalize

        return
    end subroutine UNET_summary
end module UNET_module
```

**Comment by ylikx** [comment]
Hi, sorry for the late reply.
Maybe this helps: https://github.com/ylikx/forpy/wiki/Working-with-arrays#accessing-array-elements-with-ndarrayget_data

I think the most efficient way would be to keep working with the Fortran pointer which points to the internal representation of the numpy array. Unfortunately one has to then keep working with the transpose on the Fortran side.
Sometimes it might be possible to write the Python part in a way that it produces not the original matrix but the transpose (in C order). Then in Fortran one could work with the original matrix (this time in Fortran order).
