### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by mgovoni-devel** [ylikx/forpy#9]
So far I see that python print statements are flushed only when forpy is finalized. 
Is there a way to flush the output when the python module is invoked? Unfortunately we cannot init/finalize multiple times.

**Comment by ylikx** [comment]
You can try the equivalent of the following Python code [1]:
```Python
import sys
sys.stdout.flush()
```

Fortran:
```Fortran
type(module_py) :: sys
type(object) :: stdout

! [...]

ierror = import_py(sys, "sys")
ierror = sys%getattribute(stdout, "stdout")
ierror = call_py_noret(stdout, "flush")

! [...]

call sys%destroy
call stdout%destroy
```

[1] https://stackoverflow.com/questions/230751/how-to-flush-output-of-print-function

**Comment by mgovoni-devel** [comment]
Thanks. It works.
